[workspace]
resolver = "2"
members = [
    "algorithm",
    "leetcode",
    "workbench/cargo-demo",
    "workbench/closure-demo",
    "workbench/ffi-demo",
    "workbench/generic-demo",
    "workbench/list",
    "workbench/macro-demo",
    "workbench/mod-demo",
    "workbench/tokio-demo",
    "workbench/minigrep",
    "workbench/phantom-demo",
    "tmp",
]
