[workspace]
members = [
    "algorithm",
    "leetcode",
    "workbench/cargo-demo",
    "workbench/closure-demo",
    "workbench/ffi-demo",
    "workbench/generic-demo",
    "workbench/macro-demo",
    "workbench/tokio-demo",
    "workbench/minigrep",
    "tmp"
]
