[package]
name = "cxx-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1", features = ["c++14", "c++17", "c++20"] }

[build-dependencies]
cxx-build = "1"
